<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Kootam.Framework.Domain" Version="1.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Aggregates\ApplicationAgg\" />
      <Folder Include="Aggregates\FileAgg\" />
      <Folder Include="Aggregates\FolderAgg\" />
      <Folder Include="Aggregates\TrashAgg\" />
      <Folder Include="Events\" />
      <Folder Include="Policies\" />
    </ItemGroup>

</Project>
