<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Common\" />
      <Folder Include="Events\" />
      <Folder Include="Requests\Applications\" />
      <Folder Include="Requests\Files\" />
      <Folder Include="Requests\Folders\" />
      <Folder Include="Requests\Trash\" />
      <Folder Include="Responses\" />
    </ItemGroup>

</Project>
