<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Kootam.Authentication.Jwt" Version="1.0.0" />
        <PackageReference Include="Kootam.Framework.Presentations" Version="1.0.0" />
        <PackageReference Include="Kootam.Utilities.ScalarRegistration" Version="1.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FileManager.Infrastructure\FileManager.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Authorization\" />
    </ItemGroup>

</Project>
